from typing import Protocol
from macr.investigation.records import BackendCapabilities, BackendJobState, CheckResult, CheckSpec, SnapshotRef


class ExecutionBackend(Protocol):
    def capabilities(self) -> BackendCapabilities: ...
    def run(self, check: CheckSpec, snapshot: SnapshotRef) -> CheckResult: ...
    def stop(self, check_id: str) -> BackendJobState: ...
    def inspect(self, check_id: str) -> BackendJobState: ...
